name: Build and Deploy MyWebsite

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Source
        uses: actions/checkout@v1
      - name: Build Site
        run: swift run BTCRUCLUB
      - name: Deploy Content
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          EXTERNAL_REPOSITORY: lxlxdan/BTCRUCLUB
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./Output
        with:
          commitMessage: ${{ github.event.head_commit.message }}
